# Dependencies
markdown:            kramdown
highlighter:         rouge

# Gems (for Jekyll 3.0)
gems: [jekyll-paginate]

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:year/:month/:day/:title

# Setup
title:               Stardust's Blog
tagline:             'A Hacker like jekyll theme'
description:         '计算机科学|程序设计|创业者'
url:                 https://gitlab.com/finalxcode
baseurl:             /
paginate:            7

# About/contact
author:
  name:              Stardust
  url:               https://gitlab.com/finalxcode
  email:             finalxcode@gmail.com

# Custom vars
version:             2.0

# Social Media
github:				https://gitlab.com/finalxcode
twitter:			https://gitlab.com/finalxcode
disqus:             finalxcode

# Theme Author (Please don't edit this line cause of MIT LICENSE rules)
theme:
  creator:			Rizky Ariestiyansyah
  codename:			Naringu
  link:             https://github.com/ariestiyansyah/naringu
